name: Spring Boot CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven
      
      - name: Make Maven Wrapper executable
        run: chmod +x mvnw

      - name: Build JAR 
        run: ./mvnw clean package -DskipTests

      - name: Copy JAR to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "target/*.jar"
          target: "/home/ubuntu/app"
          strip_components: 1

      - name: Restart App
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # 1. Kill old process
            pgrep -f 'java -jar' | xargs kill -9 || true
            
            cd /home/${{ secrets.EC2_USERNAME }}/app
            
            # 2. Run with memory limits!
            # We use 512MB max for a 1GB RAM server
            nohup java -Xms128m -Xmx512m -jar *.jar > app.log 2>&1 &
            
            sleep 15
            
            if grep -q "Started" app.log || grep -q "JVM running" app.log; then
              echo "Application started successfully."
            else
              echo "Startup failed. Checking logs..."
              tail -n 50 app.log
              exit 1
            fi